# Generated by Django 2.2.6 on 2019-10-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
