# Generated by Django 2.2.6 on 2019-10-09 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vassals',
            field=models.ManyToManyField(blank=True, related_name='_user_vassals_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
