# Generated by Django 2.2.6 on 2019-10-09 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_vassals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vassals',
        ),
        migrations.AddField(
            model_name='user',
            name='liege',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vassals', to=settings.AUTH_USER_MODEL),
        ),
    ]
