# Generated by Django 2.2.6 on 2019-10-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_diplomats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diplomats',
            options={'verbose_name': 'Dyplomaci', 'verbose_name_plural': 'Dyplomaci'},
        ),
        migrations.AddField(
            model_name='user',
            name='recruits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='soldiers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='gold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
