# Generated by Django 2.2.6 on 2020-02-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191017_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_check_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
