# Generated by Django 2.2.6 on 2020-02-23 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_last_check_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'Wojna wasalizacyja'), (1, 'Bunt'), (2, 'Wewnętrzna wojna o chwałę'), (3, 'Zewnętrzna wojna o chwałę')])),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wars_attacker', to=settings.AUTH_USER_MODEL)),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wars_defender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
