# Generated by Django 2.2.6 on 2020-02-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_war'),
    ]

    operations = [
        migrations.AddField(
            model_name='war',
            name='attacker_strength',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='war',
            name='defender_strength',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
