# Generated by Django 2.2.6 on 2020-04-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200224_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='war',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Aktywna'), (1, 'Zakończona')], default=0),
        ),
    ]
