BASE_GOLD_PER_SECOND = 1
TITLES = {
    100: ['Baron', BASE_GOLD_PER_SECOND * 1],
    250: ['Hrabia', BASE_GOLD_PER_SECOND * 3],
    600: ['Książe', BASE_GOLD_PER_SECOND * 5],
    1400: ['Król', BASE_GOLD_PER_SECOND * 10],
    3000: ['Cesarz', BASE_GOLD_PER_SECOND * 25]
}

BASE_DIPLOMAT_COST = 20
BASE_SOLDIER_COST = 100

DAILY_RECRUIT_INCOME=20